### ISSUE TITLE
Leaked PAT in Notebook

### ISSUE THREAD

**Issue by evamaxfield** [victorhu3/NAICS-Repository-Classification#1]
Hey @victorhu3! I'm Eva and I was on the call which your team presented results on this work! Great job btw.

I was looking through this repo again and saw that you had leaked a PAT (personal access token) in one of the notebooks. It's in the feature extraction bit.

You should delete that PAT if you haven't!

**Comment by victorhu3** [comment]
Oh no! 

Thanks for the heads up, I've updated it and told the person to delete their key.
